image: continuumio/miniconda3:latest

stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/opt/cache/pip"

cache:
  paths:
    - /opt/cache/pip

before_script:
  - apt-get update -q -y
  - apt-get install -y build-essential
  - conda env create -f .environment.yml
  - source activate tomo_env
  - python setup.py build_ext --inplace

tests:
  stage: test
  script:
    - source activate tomo_env
    - pip install coverage coverage-badge pyyaml
    - pip install pylint
    - pylint --errors-only tomo
    - coverage run -m pytest -v unit_tests/*/test*.py
    - coverage report -m
    - coverage html
    - coverage-badge -o coverage.svg
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    paths:
      - htmlcov/*
      - coverage.svg
    expire_in: 1 day

pep8:
  # Checks for conformity to PEP8 style guidelines
  stage: test
  script:
    - source activate tomo_env
    - pip install flake8
    - flake8 --count

  only:
    - merge_requests
  allow_failure: true

build-wheels:
  image: quay.io/pypa/manylinux2010_x86_64
  stage: build
  before_script: []
  script:
    - bash tools/build-wheels.sh
  variables:
    PLAT: manylinux2010_x86_64
  artifacts:
    expire_in: 7 days
    paths:
      - wheelhouse/longitudinal_tomography*.whl
  only:
    - master
    - nightly
    - tags

build-sdist:
  image: python:3
  stage: build
  before_script: []
  script: python setup.py sdist
  artifacts:
    expire_in: 7 days
    paths:
      - dist/*.tar.gz
  only:
    - master
    - nightly
    - tags

pypi:
  image: python:3
  stage: deploy
  dependencies:
    - build-wheels
    - create-sdist
  before_script: []
  script:
    - pip install -U twine
    # upload to testpypi first for error checking
    - twine upload -r testpypi --username __token__ --password $TWINE_TESTPYPI_PASSWORD wheelhouse/longitudinal_tomography*.whl dist/*.tar.gz
    # upload to pypi
    - twine upload --username $TWINE_USERNAME --password $TWINE_PYPI_PASSWORD wheelhouse/longitudinal_tomography*.whl dist/*.tar.gz
  only:
    - tags

docs:
  stage: deploy
  script:
    - source activate tomo_env
    - mv htmlcov/ public/
    - pip install sphinx sphinxcontrib-napoleon sphinx-rtd-theme
    - cd __doc
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

