tests:
  stage: test
  image: continuumio/miniconda3:latest
  before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - apt-get update -q -y
  - apt-get install -y build-essential
  - conda env create -f .environment.yml
  - source activate tomo_env
  script:
    - echo "Installing coverage"
    - pip install coverage
    - pip install coverage-badge
    - coverage run -m pytest -v unit_tests/test*.py
    - coverage report -m
    - coverage html
    - coverage-badge -o coverage.svg
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    paths:
      - htmlcov/*
      - coverage.svg
    expire_in: 1 day

pages:
  stage: deploy
  dependencies:
    - tests
  script:
    - mv htmlcov/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days











